version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: interview_backend
    ports:
      - "8000:8000"
    volumes:
      - ./uploads:/app/uploads
      # Uncomment if you want to sync code for development
      # - ./backend:/app
    env_file:
      - ./backend/.env
    restart: always

  frontend:
    build:
      context: ./Front-end
    container_name: interview_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always

volumes:
  uploads_data:
