import os
from dotenv import load_dotenv
from app.db.mongo_db import (
    candidates_collection,
    interviews_collection,
    answers_collection,
    admins_collection,
    companies_collection,
    interview_sessions_collection,
    plans_collection,
    credit_requests_collection,
    notifications_collection,
    omni_call_logs_collection,
    jobs_collection,
    job_applications_collection,
    conversation_flows_collection,
    counters_collection,
    payment_orders_collection,
    pending_signups_collection,
    security_logs_collection,
    security_policies_collection,
    copilot_sessions_collection,
    credit_ledger_collection,
    messages_collection,
    demo_requests_collection,
    contact_requests_collection,
    crash_logs_collection,
    agents_collection,
    platform_settings_collection,
    get_next_sequence_value,
)

load_dotenv()

__all__ = [
    "candidates_collection",
    "interviews_collection",
    "answers_collection",
    "admins_collection",
    "companies_collection",
    "interview_sessions_collection",
    "plans_collection",
    "credit_requests_collection",
    "notifications_collection",
    "omni_call_logs_collection",
    "jobs_collection",
    "job_applications_collection",
    "conversation_flows_collection",
    "counters_collection",
    "payment_orders_collection",
    "pending_signups_collection",
    "security_logs_collection",
    "security_policies_collection",
    "copilot_sessions_collection",
    "credit_ledger_collection",
    "messages_collection",
    "demo_requests_collection",
    "contact_requests_collection",
    "crash_logs_collection",
    "agents_collection",
    "platform_settings_collection",
    "get_next_sequence_value",
]
