import sys

with open('services.py', 'r', encoding='utf-8') as f:
    lines = f.readlines()

new_lines = lines[:1897] + [
'            </div>\n',
'        </div>\n',
'    </body>\n',
'    </html>\n',
'    \"\"\"\n',
'\n',
'def compute_invite_send_at(scheduled_start: str = \"\") -> Optional[datetime]:\n',
'    start_dt = parse_iso_datetime(scheduled_start)\n',
'    if not start_dt:\n',
'        return None\n',
'    return start_dt - timedelta(minutes=15)\n',
'\n',
'def queue_or_send_interview_email(session_doc: Dict[str, Any], link_url: str, skip_db_update: bool = False) -> Dict[str, Any]:\n',
'    scheduled_start = session_doc.get(\"scheduled_start\", \"\")\n',
'    send_at = compute_invite_send_at(scheduled_start)\n',
'    now = datetime.now(timezone.utc)\n',
'\n',
'    if send_at and send_at > now:\n',
'        if not skip_db_update:\n',
'            interview_sessions_collection.update_one(\n',
'                {\"_id\": session_doc[\"_id\"]},\n',
'                {\"$set\": {\n',
'                    \"invite_email_status\": \"pending\",\n',
'                    \"invite_email_send_at\": send_at.isoformat(),\n',
'                    \"invite_email_sent_at\": None\n',
'                }}\n',
'            )\n',
'        return {\n',
'            \"email_sent\": False,\n',
'            \"email_scheduled\": True,\n',
'            \"email_send_at\": send_at.isoformat()\n',
'        }\n',
'\n',
'    # Celery: Push email sending to background\n',
'    from app import tasks  # local import to avoid circular imports\n',
'    tasks.send_email_task.delay(\n',
'        candidate_email=session_doc.get(\"candidate_email\", \"\"),\n',
'        candidate_name=session_doc.get(\"candidate_name\", \"\"),\n',
'        link_url=link_url,\n',
'        duration=session_doc.get(\"interview_duration\", 30),\n',
'        job_description=session_doc.get(\"job_description\", \"\"),\n',
'        custom_html=session_doc.get(\"custom_email_html\", \"\"),\n',
'        scheduled_start=session_doc.get(\"scheduled_start\", \"\"),\n',
'        scheduled_end=session_doc.get(\"scheduled_end\", \"\")\n',
'    )\n',
'    email_sent = True # Async operation queued successfully\n',
'\n',
'    if not skip_db_update:\n',
'        interview_sessions_collection.update_one(\n',
'            {\"_id\": session_doc[\"_id\"]},\n',
'            {\"$set\": {\n',
'                \"invite_email_status\": \"sent\" if email_sent else \"failed\",\n',
'                \"invite_email_send_at\": (send_at.isoformat() if send_at else now.isoformat()),\n',
'                \"invite_email_sent_at\": (now.isoformat() if email_sent else None)\n',
'            }}\n',
'        )\n',
'    return {\n',
'        \"email_sent\": email_sent,\n',
'        \"email_scheduled\": False,\n',
'        \"email_send_at\": (send_at.isoformat() if send_at else now.isoformat())\n',
'    }\n',
'\n',
] + lines[2196:]

with open('services.py', 'w', encoding='utf-8') as f:
    f.writelines(new_lines)
print('Fixed merge conflict')
